# Github workflow to build and upload the documentation to Github pages.

name: Documentation

on:
  push:
    branches: [ v0.x.x ]
  pull_request:
    branches: [ v0.x.x ]

jobs:
  doc:
      name: Deploy documentation
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Install Node.js
          uses: actions/setup-node@v1

        - name: Build documentation
          if: github.event_name == 'push'
          run: |
            npm run docs
            # Remove gh-branch if it already exists, check it out
            git branch -D gh-pages || true
            git checkout --orphan gh-pages
            # Remove all staged files - We only need the docs
            git rm -rf $(git ls-files)
            # We can have some leftover files (e.g. build)
            # So add docs (which is only what we need), then `git mv` it.
            git add docs/
            git mv -k docs/* ./
            # Configure user (because persist-credentials does not persist everything...)
            git config --global user.name  "${{ github.actor }}"
            git config --global user.email "${{ github.actor }}@users.noreply.github.com"
            # We're done
            git commit -m "Documentation for commit ${{ github.sha }}"
            git push -f ${{ github.event.repository.clone_url }} gh-pages:gh-pages
